services:
  - type: web
    name: danielepauli-coaching
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /survey
        destination: /survey/index.html
      - type: rewrite
        source: /ergebnis
        destination: /ergebnis/index.html
      - type: rewrite
        source: /admin
        destination: /admin/index.html
